# Generated by Django 5.0.14 on 2026-05-10 16:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Project name, e.g., 'Lekki Phase 1'",
                        max_length=200,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Project location, e.g., 'Lekki, Lagos'",
                        max_length=300,
                    ),
                ),
                (
                    "client",
                    models.CharField(
                        blank=True, help_text="Client name", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Project description"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("ON_HOLD", "On Hold"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        help_text="Name of engineer who created the project",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "db_table": "projects",
                "ordering": ["-created_at"],
            },
        ),
    ]
