# Generated by Django 5.0.14 on 2026-05-26 06:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('piles', '0005_alter_pile_pile_type'),
        ('projects', '0002_projectmembership_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('PILE_DRIVING', 'Pile Driving')], db_index=True, default='PILE_DRIVING', max_length=40)),
                ('current_state', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('RETURNED_FOR_CORRECTION', 'Returned for Correction'), ('REJECTED', 'Rejected'), ('CERTIFIED', 'Certified'), ('LOCKED', 'Locked')], db_index=True, default='DRAFT', max_length=40)),
                ('current_version_no', models.PositiveIntegerField(default=0)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracted_execution_records', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_execution_records', to=settings.AUTH_USER_MODEL)),
                ('pile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_records', to='piles.pile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_records', to='projects.project')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_execution_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'execution_records',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionRecordVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_no', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('submitted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('data_snapshot', models.JSONField(default=dict)),
                ('source_record_hash', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='execution.executionrecord')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_record_versions', to=settings.AUTH_USER_MODEL)),
                ('supersedes_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='execution.executionrecordversion')),
            ],
            options={
                'db_table': 'execution_record_versions',
                'ordering': ['-version_no'],
            },
        ),
        migrations.AddField(
            model_name='executionrecord',
            name='latest_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='execution.executionrecordversion'),
        ),
        migrations.CreateModel(
            name='PileDrivingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('reported_depth_m', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('verified_depth_m', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('hammer_type', models.CharField(max_length=100)),
                ('hammer_energy', models.CharField(blank=True, max_length=100)),
                ('final_set', models.CharField(blank=True, max_length=100)),
                ('total_blows', models.PositiveIntegerField(default=0)),
                ('remarks', models.TextField(blank=True)),
                ('contractor_comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('execution_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pile_driving_record', to='execution.executionrecord')),
                ('pile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driving_records', to='piles.pile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pile_driving_records', to='projects.project')),
            ],
            options={
                'db_table': 'pile_driving_records',
                'ordering': ['-start_time', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DrivingResistanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_no', models.PositiveIntegerField()),
                ('depth_from_m', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('depth_to_m', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('penetration_mm', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('blow_count', models.PositiveIntegerField()),
                ('set_per_blow', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True)),
                ('driving_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resistance_logs', to='execution.piledrivingrecord')),
            ],
            options={
                'db_table': 'driving_resistance_logs',
                'ordering': ['sequence_no', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='executionrecordversion',
            constraint=models.UniqueConstraint(fields=('execution_record', 'version_no'), name='unique_execution_record_version'),
        ),
        migrations.AddIndex(
            model_name='executionrecord',
            index=models.Index(fields=['project', 'current_state'], name='execution_r_project_8261e6_idx'),
        ),
        migrations.AddIndex(
            model_name='executionrecord',
            index=models.Index(fields=['pile', 'record_type'], name='execution_r_pile_id_2a8279_idx'),
        ),
        migrations.AddIndex(
            model_name='piledrivingrecord',
            index=models.Index(fields=['project', 'start_time'], name='pile_drivin_project_57afff_idx'),
        ),
        migrations.AddIndex(
            model_name='piledrivingrecord',
            index=models.Index(fields=['pile', 'start_time'], name='pile_drivin_pile_id_7a9afd_idx'),
        ),
        migrations.AddConstraint(
            model_name='drivingresistancelog',
            constraint=models.UniqueConstraint(fields=('driving_record', 'sequence_no'), name='unique_driving_record_log_sequence'),
        ),
    ]
