# Generated by Django 5.0.14 on 2026-05-29 14:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("execution", "0001_initial"),
        ("projects", "0002_projectmembership_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EvidenceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="evidence/%Y/%m/%d/")),
                ("original_filename", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=120)),
                ("file_size", models.PositiveBigIntegerField()),
                ("sha256_hash", models.CharField(db_index=True, max_length=64)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "captured_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "gps_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "gps_lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("device_metadata", models.JSONField(blank=True, default=dict)),
                (
                    "evidence_type",
                    models.CharField(
                        choices=[
                            ("photo", "Photo"),
                            ("video", "Video"),
                            ("document", "Document"),
                            ("field_note", "Field Note"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=40,
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=40,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_items",
                        to="projects.project",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_evidence_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_evidence_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "evidence_items",
                "ordering": ["-uploaded_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="EvidenceLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "linked_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "evidence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="links",
                        to="evidence.evidenceitem",
                    ),
                ),
                (
                    "execution_record_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence_links",
                        to="execution.executionrecordversion",
                    ),
                ),
                (
                    "linked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evidence_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "evidence_links",
                "ordering": ["-is_primary", "linked_at", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="evidenceitem",
            index=models.Index(
                fields=["project", "evidence_type"],
                name="evidence_it_project_3aae16_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="evidenceitem",
            index=models.Index(
                fields=["project", "verification_status"],
                name="evidence_it_project_73a60b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="evidenceitem",
            index=models.Index(
                fields=["uploaded_by", "uploaded_at"],
                name="evidence_it_uploade_f7b84d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="evidencelink",
            index=models.Index(
                fields=["execution_record_version", "is_primary"],
                name="evidence_li_executi_c6e091_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="evidencelink",
            index=models.Index(
                fields=["evidence", "linked_at"], name="evidence_li_evidenc_778a5f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="evidencelink",
            constraint=models.UniqueConstraint(
                fields=("evidence", "execution_record_version"),
                name="unique_evidence_version_link",
            ),
        ),
    ]
