# Generated by Django 5.0.14 on 2026-05-10 16:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PileTypeConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pile_type', models.CharField(choices=[('TYPE_I', 'Type I'), ('TYPE_II', 'Type II'), ('TYPE_III', 'Type III')], db_index=True, help_text='Pile type identifier', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of this pile type configuration')),
                ('main_bar_sections', models.JSONField(default=list, help_text='List of main bar sections with size, length, count')),
                ('lap_length_m', models.FloatField(default=0.0, help_text='Lap length in meters', validators=[django.core.validators.MinValueValidator(0)])),
                ('helix_bar_size_mm', models.PositiveIntegerField(default=8, help_text='Helix/spiral bar diameter in mm (e.g., 8 for Y8)')),
                ('helix_pitch_mm', models.PositiveIntegerField(default=250, help_text='Helix pitch/spacing in mm')),
                ('cage_diameter_mm', models.PositiveIntegerField(default=480, help_text='Reinforcement cage diameter in mm')),
                ('helix_end_turns', models.PositiveIntegerField(default=8, help_text='Extra end turns beyond design_length/pitch')),
                ('stiffener_bar_size_mm', models.PositiveIntegerField(default=16, help_text='Stiffener ring bar diameter in mm')),
                ('stiffener_ring_diameter_mm', models.FloatField(default=543.6, help_text='Stiffener ring centerline diameter in mm')),
                ('stiffener_spacing_m', models.FloatField(default=2.5, help_text='Stiffener spacing along pile length in meters', validators=[django.core.validators.MinValueValidator(0.1)])),
                ('concrete_cover_mm', models.PositiveIntegerField(default=20, help_text='Concrete cover to reinforcement in mm')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this configuration is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pile Type Configuration',
                'verbose_name_plural': 'Pile Type Configurations',
                'db_table': 'pile_type_configurations',
                'ordering': ['pile_type'],
            },
        ),
        migrations.CreateModel(
            name='Pile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pile_no', models.CharField(help_text="Pile identifier, e.g., 'P-001', 'PILE 1 OF TYPE II'", max_length=50)),
                ('pile_type', models.CharField(choices=[('TYPE_I', 'Type I'), ('TYPE_II', 'Type II'), ('TYPE_III', 'Type III')], db_index=True, help_text='Pile type determines reinforcement configuration', max_length=20)),
                ('diameter_mm', models.PositiveIntegerField(default=500, help_text='Pile diameter in mm', validators=[django.core.validators.MinValueValidator(200), django.core.validators.MaxValueValidator(2000)])),
                ('design_length_m', models.FloatField(help_text='Design length in meters', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(100.0)])),
                ('actual_length_m', models.FloatField(help_text='Actual installed length in meters', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(100.0)])),
                ('piling_method', models.CharField(blank=True, help_text="Piling method, e.g., 'Driven Cast In-Situ'", max_length=100)),
                ('concrete_grade', models.CharField(blank=True, help_text="Concrete grade, e.g., 'C35/40'", max_length=20)),
                ('location_on_site', models.CharField(blank=True, help_text='Location on site', max_length=200)),
                ('drawing_reference', models.CharField(blank=True, help_text='Drawing reference number', max_length=100)),
                ('date_installed', models.DateField(blank=True, help_text='Date of installation', null=True)),
                ('notes', models.TextField(blank=True, help_text='Obstructions, remarks, test results')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piles', to='projects.project')),
            ],
            options={
                'verbose_name': 'Pile',
                'verbose_name_plural': 'Piles',
                'db_table': 'piles',
                'ordering': ['pile_no'],
                'unique_together': {('project', 'pile_no')},
            },
        ),
        migrations.CreateModel(
            name='PileCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_bars_kg', models.FloatField(default=0.0, help_text='Total main bar weight in kg')),
                ('helix_kg', models.FloatField(default=0.0, help_text='Total helix/spiral weight in kg')),
                ('stiffeners_kg', models.FloatField(default=0.0, help_text='Total stiffener ring weight in kg')),
                ('total_steel_kg', models.FloatField(default=0.0, help_text='Grand total steel weight in kg')),
                ('design_concrete_m3', models.FloatField(default=0.0, help_text='Concrete volume using design length')),
                ('actual_concrete_m3', models.FloatField(default=0.0, help_text='Concrete volume using actual length')),
                ('calculation_version', models.CharField(default='1.0.0', help_text='Version of calculation engine used', max_length=20)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('pile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calculation', to='piles.pile')),
            ],
            options={
                'verbose_name': 'Pile Calculation',
                'verbose_name_plural': 'Pile Calculations',
                'db_table': 'pile_calculations',
            },
        ),
    ]
