# Generated by Django 5.0.14 on 2026-05-12 12:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("piles", "0002_pile_unique_project_pile"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="pile",
            unique_together=set(),
        ),
    ]
