# Generated by Django 5.0.14 on 2026-05-29 14:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("execution", "0001_initial"),
        ("piles", "0005_alter_pile_pile_type"),
        ("projects", "0002_projectmembership_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VarianceFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("depth", "Depth"),
                            ("blow_count", "Blow Count"),
                            ("concrete", "Concrete"),
                            ("reinforcement", "Reinforcement"),
                            ("evidence", "Evidence"),
                            ("approval", "Approval"),
                            ("delay", "Delay"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("acknowledged", "Acknowledged"),
                            ("resolved", "Resolved"),
                            ("waived", "Waived"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=40,
                    ),
                ),
                ("expected_value", models.CharField(blank=True, max_length=255)),
                ("reported_value", models.CharField(blank=True, max_length=255)),
                ("verified_value", models.CharField(blank=True, max_length=255)),
                ("message", models.TextField()),
                ("rule_code", models.CharField(max_length=80)),
                (
                    "triggered_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_comment", models.TextField(blank=True)),
                (
                    "execution_record_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="variance_flags",
                        to="execution.executionrecordversion",
                    ),
                ),
                (
                    "pile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variance_flags",
                        to="piles.pile",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variance_flags",
                        to="projects.project",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_variance_flags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "variance_flags",
                "ordering": ["-triggered_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="VerificationActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(db_index=True, max_length=80)),
                ("previous_status", models.CharField(blank=True, max_length=40)),
                ("new_status", models.CharField(blank=True, max_length=40)),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verification_action_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "variance_flag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_logs",
                        to="verification.varianceflag",
                    ),
                ),
            ],
            options={
                "db_table": "verification_action_logs",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="varianceflag",
            index=models.Index(
                fields=["project", "status"], name="variance_fl_project_6d1e72_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="varianceflag",
            index=models.Index(
                fields=["pile", "category"], name="variance_fl_pile_id_7b3674_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="varianceflag",
            index=models.Index(
                fields=["severity", "status"], name="variance_fl_severit_4bbee2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="varianceflag",
            index=models.Index(
                fields=["triggered_at"], name="variance_fl_trigger_9b3795_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="varianceflag",
            constraint=models.UniqueConstraint(
                fields=("execution_record_version", "rule_code"),
                name="unique_variance_flag_per_version_rule",
            ),
        ),
        migrations.AddIndex(
            model_name="verificationactionlog",
            index=models.Index(
                fields=["variance_flag", "created_at"],
                name="verificatio_varianc_5c74f0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="verificationactionlog",
            index=models.Index(
                fields=["actor", "created_at"], name="verificatio_actor_i_8de431_idx"
            ),
        ),
    ]
