# Generated by Django 5.0.14 on 2026-05-30 13:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("execution", "0001_initial"),
        ("piles", "0005_alter_pile_pile_type"),
        ("projects", "0002_projectmembership_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificationPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("package_no", models.CharField(max_length=80)),
                ("description", models.TextField(blank=True)),
                (
                    "current_state",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("CERTIFIED", "Certified"),
                            ("LOCKED", "Locked"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=40,
                    ),
                ),
                ("quantity_snapshot", models.JSONField(blank=True, default=dict)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("certified_at", models.DateTimeField(blank=True, null=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_certification_packages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "certified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certified_certification_packages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_certification_packages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certification_packages",
                        to="projects.project",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_certification_packages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "certification_packages",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CertificationLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certified_depth_m",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "certified_concrete_m3",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "certified_reinforcement_kg",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("quantity_snapshot", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="certification_lines",
                        to="piles.pile",
                    ),
                ),
                (
                    "source_execution_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="certification_lines",
                        to="execution.executionrecordversion",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="certification.certificationpackage",
                    ),
                ),
            ],
            options={
                "db_table": "certification_lines",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="CertifiedQuantity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certified_depth_m",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "certified_concrete_m3",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "certified_reinforcement_kg",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("frozen_snapshot", models.JSONField(default=dict)),
                (
                    "certified_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "certification_line",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="certified_quantity",
                        to="certification.certificationline",
                    ),
                ),
                (
                    "certified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certified_quantities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="certified_quantities",
                        to="certification.certificationpackage",
                    ),
                ),
                (
                    "pile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="certified_quantities",
                        to="piles.pile",
                    ),
                ),
                (
                    "source_execution_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="certified_quantities",
                        to="execution.executionrecordversion",
                    ),
                ),
            ],
            options={
                "db_table": "certified_quantities",
                "ordering": ["certified_at", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="certificationpackage",
            index=models.Index(
                fields=["project", "current_state"],
                name="certificati_project_c0f7da_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="certificationpackage",
            index=models.Index(
                fields=["package_no"], name="certificati_package_72fe8f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="certificationpackage",
            constraint=models.UniqueConstraint(
                fields=("project", "package_no"),
                name="unique_certification_package_no_per_project",
            ),
        ),
        migrations.AddIndex(
            model_name="certificationline",
            index=models.Index(
                fields=["package", "pile"], name="certificati_package_acde06_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="certificationline",
            index=models.Index(
                fields=["source_execution_version"],
                name="certificati_source__ce7216_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="certificationline",
            constraint=models.UniqueConstraint(
                fields=("package", "source_execution_version"),
                name="unique_certification_line_source_version_per_package",
            ),
        ),
        migrations.AddIndex(
            model_name="certifiedquantity",
            index=models.Index(
                fields=["package", "pile"], name="certified_q_package_d0faa8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="certifiedquantity",
            index=models.Index(
                fields=["source_execution_version"],
                name="certified_q_source__5a6c4f_idx",
            ),
        ),
    ]
