# Generated by Django 5.0.14 on 2026-06-13 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("certification", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="certifiedquantity",
            options={
                "ordering": ["certified_at", "id"],
                "verbose_name": "Certified Quantity",
                "verbose_name_plural": "Certified Quantities",
            },
        ),
    ]
