# Generated by Django 5.0.14 on 2026-05-31 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
        ("piles", "0005_alter_pile_pile_type"),
        ("projects", "0002_projectmembership_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditevent",
            options={},
        ),
        migrations.AlterModelOptions(
            name="domainevent",
            options={},
        ),
        migrations.AlterModelOptions(
            name="timelineevent",
            options={},
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="pile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="piles.pile",
            ),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="domainevent",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="domainevent",
            name="pile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="piles.pile",
            ),
        ),
        migrations.AlterField(
            model_name="domainevent",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="timelineevent",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="timelineevent",
            name="pile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="piles.pile",
            ),
        ),
        migrations.AlterField(
            model_name="timelineevent",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="projects.project",
            ),
        ),
    ]
